<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="EscreveBD" Id="{eae73980-1c52-4c41-a457-2040f5753823}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EscreveBD
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EscreveBD">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>